job:
  package-manager: vcpkg
  source:
    provider: github
    repo: jamiemagee/dependabot-vcpkg
    directories:
      - builtin-baseline
    branch: main
credentials:
  - type: git_source
    host: github.com
    username: x-access-token
    password: $GITHUB_TOKEN
